### PR TITLE
Fix Karpenter addon not return null for instanceStorePolicy as default

### PR DESCRIPTION
**Pull request by vumdao**
*Issue #, if available:*
```
7:34:19 PM | UPDATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | selvcd1deveksbluep...detemplate2CEE3EE4
Received response status [FAILED] from custom resource. Message returned: Error: b'The EC2NodeClass "default-ec2nodeclass" is invalid: \n* spec.instanceStorePolicy: Unsupported value: "": supported values: "RAID0"\n* <
nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation\n'

Logs: /aws/lambda/DeployDev-sel-vc-d1-dev-eks-bluepr-Handler886CB40B-h954A8KfTkdY
```

*Description of changes:*
Return null value for instanceStorePolicy as default value

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by youngjeong46 — APPROVED** [review]
Thanks for submitting the PR, this was missed on the last release. 

LGTM!

**Comment by shapirov103** [comment]
Pending e2e. (Test account is in maintenance mode atm, ETA 1 day).

**Comment by vumdao** [comment]
@shapirov103 When will we have a release/hotfix for this, my blueprint project is being failed without this.

**Comment by shapirov103** [comment]
@vumdao planning today or Monday.

**Comment by shapirov103** [comment]
1.14.1 is out.

**Pull request merged**
