### PR TITLE
Feature: Paralus addon

### PR DESCRIPTION
**Pull request by niravparikh05**
*Issue #, if available:*
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/580

*Description of changes:*
Add support to deploy Paralus v0.2.0 to EKS using blueprints addon.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shapirov103 — COMMENTED** [review]
@niravparikh05 Thank you for your contribution!

The add-on is valuable for the blueprints. However, there are a few things that stand out atm:

The add-on must be implemented according to the extensibility guidelines: https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/

In particular sections for "Public Extensions" and (if applicable) "Partner Extensions": https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/#partner-extensions

Sensitive data must be passed according to the following section of the guide: https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/#passing-secrets-to-add-ons (done for security reasons)

Generally, you will need to host the add-on in a separate (ideally vendor) company repo and publish it through NPM to make it available with the blueprints. Then submit a PR to the patterns repository. 

Luckily, most of the work that you did will be preserved and repackaged. Please let me know if you have any questions.

**Comment by shapirov103** [comment]
@niravparikh05 following up on my previous comment: will you be able to rework this add-on implementation?

**Comment by shapirov103** [comment]
@parkand1 do you mind working with the partner to address this?

**Comment by nirav-rafay** [comment]
thanks @shapirov103 @parkand1 for your valuable comments. Yeah, I was a bit occupied with other stuff. Will have a look at your comments and get back if necessary.

**Comment by parkand1** [comment]
@niravparikh05 any updates here?

**Comment by niravparikh05** [comment]
@parkand1 thanks for following up, I was unable to get to this for a while and finally got sometime this week.

We have made changes to create paralus addon using cdk available at https://github.com/paralus/eks-blueprints-addon, npm package is also published and available at https://www.npmjs.com/package/@paralus/paralus-eks-blueprints-addon.

In addition to above, I have raised a pr with changes to add a sample eks blueprint for paralus - https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/63. 

Kindly have a look and let me know if any further changes are required.

**Review by parkand1 — APPROVED** [review]
LGTM - I was able to get it up and running on my end as well.

**Comment by parkand1** [comment]
Closing as main addon will be merged on the patterns repository

**Pull request closed without merging**
