### PR TITLE
docs: add cast to iam.Role for attribute mastersRole

### PR DESCRIPTION
**Pull request by jumic**
*Issue #, if available:* -

*Description of changes:*
Fix an invalid assignment in the documentation. `blueprints.getNamedResource("my-role")` returns an `IConstruct`. Attribute `mastersRole` expects `IRole`. This PR adds an cast to `IRole` as it is already used in other [examples](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/vpc-cni/#vpc-cni-service-account-and-irsa-config).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — APPROVED** [review]
LGTM. Thanks for the contribution.

**Comment by elamaran11** [comment]
@jumic GH Action is failing because of missing link please fix it.

**Comment by elamaran11** [comment]
@jumic Thankyou for fixing it. I know its not related to your PR. There is another failure with Kubecost URL.

**Review by elamaran11 — APPROVED** [review]
LGTM.

**Comment by jumic** [comment]
@elamaran11 Thanks for reviewing this change. 👍

**Pull request merged**
