### PR TITLE
Adding compatibility mode to avoid extra resource nesting - backwards compatibility fix.

### PR DESCRIPTION
**Pull request by shapirov103**
*Issue #, if available:* #1033

*Description of changes:* By default blueprints are created in the compatibility mode to avoid extra nesting.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shapirov103** [comment]
e2e failure potentially due to lingering SG created through ingress-nginx addon.

**Comment by shapirov103** [comment]
@bugathagit  this is the PR that will have impact on the construct, hopefully nothing major. You can apply `builder().compatibilityMode(false) to nest resources under the construct, this may be reasonable for namespacing for example. The construct id has been modified to <blueprint-id>-ct.

**Review by bugathagit — APPROVED** [review]

**Pull request merged**
