### PR TITLE
upgraded add-on versions, CDK moved to 2.92, NPM lib updates, kubectl layer for 1.27

### PR DESCRIPTION
**Pull request by shapirov103**
Lib updates

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — COMMENTED** [review]
Changes looks good to me. We need to fix e2e issues.

**Comment by shapirov103** [comment]
the e2e with 2.92. CDK produced the following error:
```
CREATE_FAILED        \| Custom::AWSCDK-EKS-Cluster            \| blueprint-construct-dev/Resource/Resource/Default (blueprintconstructdevE0DAE201) Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor
--
1040 |  
1041 | Logs: /aws/lambda/blueprint-construct-dev-aws-OnEventHandler42BEBAE0-umz1x3XxxiNR
1042 |  
1043 | at Object.<anonymous> (/var/task/index.js:1:417)
1044 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
1045 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
1046 | at Module.load (node:internal/modules/cjs/loader:1119:32)
1047 | at Module._load (node:internal/modules/cjs/loader:960:12)
1048 | at Module.require (node:internal/modules/cjs/loader:1143:19)
1049 | at require (node:internal/modules/cjs/helpers:110:18)
1050 | at _tryRequireFile (file:///var/runtime/index.mjs:912:37)
1051 | at _tryRequire (file:///var/runtime/index.mjs:962:25)
1052 | at _loadUserApp (file:///var/runtime/index.mjs:991:22) (RequestId: aa68dde1-004d-4f0f-b617-af3b3a51456b)
```

appears to be specifc to 2.92.0 CDK. Error from custom CDK resource.

**Review by elamaran11 — APPROVED** [review]
LGTM

**Pull request merged**
