### PR TITLE
Pixie Addon Documentation

### PR DESCRIPTION
**Pull request by aimichelle**
*Description of changes:* Adds documentation for the Pixie AddOn.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aimichelle** [comment]
Thanks for the review @shapirov103 ! I'm working on updating the addon to leverage the CSI secret store driver, as mentioned. Hoping to have something very soon.

**Comment by aimichelle** [comment]
@shapirov103 , just updated it to leverage the CSI secret store driver. Thanks for the suggestion!

**Review by shapirov103 — COMMENTED** [review]
Great work! 

It is probably evident to you (and me): let's add a line on add-on installation either through package.json or just with `npm i @pixie-labs/pixie-ssp-addon`.

I am validating it works now.

**Comment by aimichelle** [comment]
Good catch--just updated to include the add-on installation.
Let me know if you run into any issues. Thank you!

**Comment by shapirov103** [comment]
@aimichelle I was holding off with the merge due to the pending renaming of the repo and subsequent impact to the technical artifacts. Please review the follow and let me know if we can help in any way. 

Pixie add-on is a really cool component and I am looking forward to having it at launch and will do everything we can to support this add-on with the transition.

Going forward, the new name for the framework at launch will be *EKS Blueprints*. We are actively working on renaming both the CDK and Terraform repositories, artifacts and overall documentation to reflect the new name. For the CDK and Terraform versions of the framework, the new names will be *EKS Blueprints for CDK* and *EKS Blueprints for Terraform.*

Again, we appreciate all of your support to date and apologize for any inconvenience that the name change may have caused. Below are the instructions on how to move forward with your add-on with the new changes for launch. Thank you again and please reach out if you have any questions or comments.

*Technical Instructions for Add-on Upgrades*

*EKS Blueprints for CDK* 

The new version of the EKS Blueprints also features a transition to [CDK v2](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) (https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) which has impact on the existing add-ons. While migration to CDK v2 mostly requires update to the imports, it means changes to the code base and it also means that existing add-ons in their current shape won’t work with EKS Blueprints. 

*npm module*: “@aws-quickstart/eks-blueprints”: “0.1.1” ([https://www.npmjs.com/package/@aws-quickstart/eks-blueprints)](https://www.npmjs.com/package/@aws-quickstart/eks-blueprints) (https://www.npmjs.com/package/@aws-quickstart/eks-blueprints)
*Note*: this is a preview version, so you can choose to depend on the “latest”, since it will be 1.x at GA

*Repositories*

1. Main repo: https://github.com/aws-quickstart/cdk-eks-blueprints
2. Patterns: https://github.com/aws-samples/cdk-eks-blueprints-patterns (please use branch feature/cdk-2.x, although I had to comment out existing dependencies on partner add-on as they won’t work with this version without an upgrade)
3. Extension Example: https://github.com/shapirov103/eks-blueprints-extension


*Note*: The extension example mentioned above (fluentbit add-on) has been ported over to eks-blueprints and CDK v2.

*Ask*:

1. *[highly recommended]* Rename your npm module. Suggested names: “<your-product>-eks-blueprints-addon”.  
2. *[Highly recommended]* Rename your GitHub repository (optional): as a best practice, it is recommended to match the repository name and the artifact (npm module) name
3. *[Required]* Upgrade dependencies to use “@aws-quickstart/eks-blueprints”: “^0.1.1” (or latest). We will change the version to 1.x at GA.
4. *[Required]* Upgrade CDK version to ^2.17.0. Example of package.json: https://github.com/shapirov103/eks-blueprints-extension/blob/main/package.json
5. *[Required]* Remove extra context variables from cdk.json (not needed anymore). Example: https://github.com/shapirov103/eks-blueprints-extension/blob/main/cdk.json
6. *[Required]* Migrate your code to CDKv2. In most cases it means the following:
    Replace “@aws-cdk/” with “aws-cdk-lib”.
    For Construct, the new module name is “constructs”. See example imports [here](http://%20https//github.com/shapirov103/eks-blueprints-extension/blob/main/lib/index.ts) (http:// https://github.com/shapirov103/eks-blueprints-extension/blob/main/lib/index.ts).
    More info on CDK v2 migration [here](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) (https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html).
7. *[Required]* Publish your add-ons in npm and provide the new name. AWS will upgrade the patterns and validate. 
8. *[Required]* Validate the current documentation for your add-on on the [main repository](https://github.com/aws-quickstart/cdk-eks-blueprints/tree/main/docs/addons) (https://github.com/aws-quickstart/cdk-eks-blueprints/tree/main/docs/addons).
9. *[Required]* Update your GTM materials and documentation (could be done by AWS, please let us know). Suggested names:
    SSP => EKS Blueprints
    Amazon EKS SSP Quickstart => Amazon EKS Blueprints
    ssp-amazon-eks => eks-blueprints
    
10. *[Required]* Please provide the timeline for your portion of the upgrade (required for launch).

**Comment by shapirov103** [comment]
> michellenguyen@pixielabs.ai

Invite sent. Please feel free to ping me at any point. If you feel that getting on a call to discuss, screen share will help, I am open to do so. Looking forward to merging it and thank you!

**Comment by aimichelle** [comment]
Thank you, @shapirov103 ! Just made the changes in the pixie addon repo + these docs. Let me know if there's anything else I should be doing!
Thanks a bunch for all of your help!

**Review by shapirov103 — APPROVED** [review]
LGTM, Great work!

**Pull request merged**
