### PR TITLE
Release 1.15 Prep: library upgrades, helm upgrades, CDK moved to 2.14…

### PR DESCRIPTION
**Pull request by shapirov103**
…7.1, Default EKS version 1.30, other changes

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — COMMENTED** [review]
LGTM

**Comment by shapirov103** [comment]
e2e failure is because adot is incompatible with 1.30 and there is no version of adot to target that platform.

**Comment by shapirov103** [comment]
e2e failure due to adot not supported (yet) with 1.30. Downgrading default EKS version to 1.29

**Pull request merged**
