### PR TITLE
bugfix: Adds cluster role for otel daemonset deployment mode

### PR DESCRIPTION
**Pull request by arunvthangaraj**
*Issue #, if available:* 990

*Description of changes:* This PR adds the required cluster role for the daemonset template.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — APPROVED** [review]
LGTM.

**Comment by elamaran11** [comment]
@shapirov103 Please approve and Merge. E2E is not required.

**Review by shapirov103 — APPROVED** [review]
LGTM

**Comment by shapirov103** [comment]
> @shapirov103 Please approve and Merge. E2E is not required.

@elamaran11 aren't we deploying this addon in e2e, so if there is an error in the modified kubernetes manifest we should be able to catch it. Ideally, functional verification is also needed, e.g. similar to what we do in Conformitron. That will improve quality assurance and reduce issues from customers. 

I will look into the e2e failure.

**Comment by elamaran11** [comment]
> > @shapirov103 Please approve and Merge. E2E is not required.
> 
> @elamaran11 aren't we deploying this addon in e2e, so if there is an error in the modified kubernetes manifest we should be able to catch it. Ideally, functional verification is also needed, e.g. similar to what we do in Conformitron. That will improve quality assurance and reduce issues from customers.
> 
> I will look into the e2e failure.

@shapirov103 We do have E2E for this addon already but the `addon` supports 4 different types of modes - `deployment` `daemonset` `statefulset` and `sidecar` we cant accomodate all of these in one `e2e` deployment. So our `e2e` deploys only `deployment `mode. We can alter it but we dont use `daemonset` approach. Arun is working on a blog with `daemonset` so this was broken and this change is required. But `e2e` failure is not related to this change. So once e2e issues are fixed, we can merge this.

**Comment by elamaran11** [comment]
@shapirov103 Can this be merged?

**Comment by shapirov103** [comment]
Yes, the error on e2e was unrelated.

**Pull request merged**
