### PR TITLE
Fixing Issue #1011

### PR DESCRIPTION
**Pull request by elamaran11**
*Issue #, if available:*

*Description of changes:*
Fixing Issue #1011

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by elamaran11** [comment]
@shapirov103 This issue is fixed, i tested E2E and everything works. Please review and merge.

**Comment by elamaran11** [comment]
@shapirov103 All set to approve and merge.

**Review by aarongorka — APPROVED** [review]

**Review by shapirov103 — COMMENTED** [review]
LGTM

**Pull request merged**
