### PR TITLE
Fix for issue #531

### PR DESCRIPTION
**Pull request by bnaydenov**
*Fix for issue #531*

*Adding missing IAM policy. Check the issue #531 for more details *

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bnaydenov** [comment]
@shapirov103 please check this one.

**Review by shapirov103 — APPROVED** [review]
@bnaydenov thank you for your contribution!

We will improve the validation framework. Apparently after switching to Karpenter we lost a test case to make sure cluster autoscaler works.

**Comment by shapirov103** [comment]
I will publish 1.4.1 shortly - planning tomorrow, unless more issue are discovered.

**Comment by bnaydenov** [comment]
@shapirov103 thanks for quick reaction. I hope for no more issues

**Pull request merged**
