### PR TITLE
(fix) Fixing Karpenter IAM Policy for #463

### PR DESCRIPTION
**Pull request by javydekoning**
*Issue #, if available:*
#463

*Description of changes:*
Add `pricing:GetProducts` to policy

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by youngjeong46** [comment]
@javydekoning Thank you for submitting the PR. Can you verify that you have tested the functionality on your end? Our e2e test doesn't cover it.

Once confirmed, we can run our e2e and merge the PR.

**Comment by javydekoning** [comment]
I tested and found another missing permission. 

```
2022-08-09T15:45:49.229Z	ERROR	controller.aws.pricing	updating spot pricing, UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 80a69095-f28c-4a1c-baea-cdbe5ecb13aa, using existing pricing data from 07 Jul 22 10:58 -0500	{"commit": "062a029"}
```

Will fix this as well and confirm.

**Comment by javydekoning** [comment]
Tested and confirmed fix:

```
2022-08-09T15:55:48.953Z	INFO	controller.aws.pricing	Updating EC2 pricing information	{"commit": "062a029"}
2022-08-09T15:55:49.205Z	INFO	controller.aws.pricing	updated spot pricing with 540 instance types	{"commit": "062a029"}
2022-08-09T15:55:51.104Z	INFO	controller.aws.pricing	updated on-demand pricing with 548 instance types	{"commit": "062a029"}
```

**Pull request merged**
