### PR TITLE
Fix: allow to extend configurations of AWS LB controller and EBS CSI driver.

### PR DESCRIPTION
**Pull request by thpham**
*Issue #, if available:*

This PR resolve:

- issue #968 - allow to extend LB controller with helm values.
- issue #995 - allow ebs-csi-controller to have custom configurationValues.

*Description of changes:*

These change have been tested on my current deployment.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — COMMENTED** [review]
LGTM.

**Comment by elamaran11** [comment]
@shapirov103 Please run e2e if you are good with the change.

**Comment by thpham** [comment]
> end to end tests failed. A maintainer can provide more details.

Would it be possible to have some hints about what is failing to help me fix the e2e tests ?

Thank you !

**Comment by shapirov103** [comment]
e2e test failed on delete for what appears to be an unrelated reason: 

Failed resources:
--
2896 | blueprint-construct-dev \| 8:02:32 PM \| DELETE_FAILED        \| Custom::AWS                           \| ClusterLogsEnabler/Resource/Default (ClusterLogsEnablerD85801E8) Received response status [FAILED] from custom resource. Message returned: Package @aws-sdk/client-eks does not exist. (RequestId: 9e71a5a4-7340-4402-ab29-89394fa4c608)

We use a custom resource on cluster log enablement, it is time to refactor this functionality. We will push a PR on that, and after merging rerun e2e on this PR.

**Comment by thpham** [comment]
@shapirov103 thank you for having fixed the e2e tests ! I hope this PR might be included in your next release ! cheers.

**Review by shapirov103 — APPROVED** [review]
LGTM

**Comment by shapirov103** [comment]
> @shapirov103 thank you for having fixed the e2e tests ! I hope this PR might be included in your next release ! cheers.

All changes in main will be in the next release, either 1.14.2 or 1.15.0.

**Pull request merged**
