### PR TITLE
Upgraded the aws-otel-collector image in otel-collector-amp-collector

### PR DESCRIPTION
**Pull request by ashoksrirama**
*Issue #, if available:*

*Description of changes:*
Updated the otel-collector-amp-collector image version to v0.41.1  in otel-collector-amp-collector deployment.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ashoksrirama** [comment]
Testing results..

```bash
kubectl get deploy -n adot
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
otel-collector-amp-collector    1/1     1            1           26m
otel-collector-xray-collector   1/1     1            1           136m
```

```bash
kubectl get pods -n adot
NAME                                             READY   STATUS    RESTARTS   AGE
otel-collector-amp-collector-7fc475df74-j4bfb    1/1     Running   0          21m
otel-collector-xray-collector-6977b478d7-fzdhw   1/1     Running   0          136m
```

**Comment by elamaran11** [comment]
> Testing results..
> 
> ```shell
> kubectl get deploy -n adot -o wide
> NAME                            READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS      IMAGES                                                        SELECTOR
> otel-collector-amp-collector    1/1     1            1           25m    otc-container   public.ecr.aws/aws-observability/aws-otel-collector:v0.41.1   app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=adot.otel-collector-amp,app.kubernetes.io/managed-by=opentelemetry-operator,app.kubernetes.io/part-of=opentelemetry
> otel-collector-xray-collector   1/1     1            1           136m   otc-container   public.ecr.aws/aws-observability/aws-otel-collector:v0.41.1   app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=adot.otel-collector-xray,app.kubernetes.io/managed-by=opentelemetry-operator,app.kubernetes.io/part-of=opentelemetry
> ```
> 
> ```shell
> kubectl get pods -n adot
> NAME                                             READY   STATUS    RESTARTS   AGE
> otel-collector-amp-collector-7fc475df74-j4bfb    1/1     Running   0          21m
> otel-collector-xray-collector-6977b478d7-fzdhw   1/1     Running   0          136m
> ```

Fantastic Ashok. Let me run E2E.

**Review by elamaran11 — APPROVED** [review]
LGTM

**Comment by elamaran11** [comment]
@shapirov103 Pls check and merge;

**Review by shapirov103 — APPROVED** [review]

**Pull request merged**
