### PR TITLE
FluxCD fails to deploy multiple Kustomizations following PR #794

### PR DESCRIPTION
**Pull request by freschri**
this needs to be reviewed tested and approved by zjaco13 to check compatibility with his original use case and avoid further conflicts between the 2 PRs
see related bug report for details

### CODE REVIEW

**Comment by elamaran11** [comment]
@zjaco13 Can you check on this PR. Looks like your flux PR change broke some logic for @freschri to test his flux multi path implementation. Please review and run this from your end.

**Review by elamaran11 — APPROVED** [review]
LGTM with Zach's changes

**Comment by elamaran11** [comment]
@shapirov103 This has Zach's and Riccard's changes.

**Review by shapirov103 — APPROVED** [review]
LGTM

**Pull request merged**
