### PR TITLE
fix(addons/karpenter): merge user provided `settings.aws` values with addon provided values.

### LINKED ISSUE #802: Karpenter: Cannot configure `settings.aws` helm values when chart version >= 0.19.0
### Describe the bug

Any helm values provided to the karpenter addon under `settings.aws` are overridden are lost.

### Expected Behavior

User provided values should be merged with the values provided by the addon.

### Current Behavior

Due to the following code snippet:
https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/karpenter/index.ts#L278-L284

All user provided values are dropped.

### Reproduction Steps

```ts
new blueprints.KarpenterAddOn({
	version: 'v0.29.2',
	requirements: [
		{ key: Label.ARCH, op: 'In', vals: ['arm64'] },
		{ key: Label.CAPACITY_TYPE, op: 'In', vals: ['spot', 'on-demand'] },
		{ key: Label.INSTANCE_CATEGORY, op: 'In', vals: ['c', 'm', 'r', 't'] },
		{ key: Label.INSTANCE_HYPERVISOR, op: 'In', vals: ['nitro'] },
	],
	subnetTags: {
		Name: subnetNames,
	},
	securityGroupTags: {
		[clusterDiscoveryTag]: 'owned',
	},
	amiFamily: 'AL2',
	consolidation: { enabled: true },
	interruptionHandling: true,
	namespace: 'karpenter',
	values: {
	  // these values get overridden and lost!
		settings: {
			aws: {
				// informs karpenter to expect prefix delegation.
				enableENILimitedPodDensity: false,
			},
		},
	},
	// refresh nodes at least every 30 days
	ttlSecondsUntilExpired: 2592000,
})

```

Then running `helm get values -n karpenter`:
```
USER-SUPPLIED VALUES:
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: xxxxxxxxxxxxxxxxx
  create: false
  name: blueprints-addon-karpenter
settings:
  aws:
    clusterEndpoint: xxxxxxxxxxxxxxx
    clusterName: xxxxxxxxxxxxxxx
    defaultInstanceProfile: xxxxxxxxxxxxx
    interruptionQueueName: development-development-blueprint
```

### Possible Solution

Merge any user provided values with the values set.

### Additional Information/Context

_No response_

### CDK CLI Version

2.88.0 (build 5d497f9)

### EKS Blueprints Version

1.10.1

### Node.js Version

v18.16.0

### Environment details (OS name and version, etc.)

N/A

### Other information

_No response_

### PR DESCRIPTION
**Pull request by BradenM**
_Issue #, if available:_
Closes #802

_Description of changes:_

- Added initially failing unit test demonstrating the issue.
- Made test green by merging user provided values with the addon provided values.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shapirov103 — APPROVED** [review]
@BradenM Looks great, thank you for your contribution. 
@youngjeong46 please take a look as well. 

I will kick off e2e test.

**Comment by BradenM** [comment]
@shapirov103 Interesting. Am I able to view logs of the e2e tests anywhere?

Should I rebase this branch onto the latest changes from main?

**Comment by shapirov103** [comment]
@BradenM there was a failure from the previous run, which failed to deprovision the stack. So subsequent runs failed. Now it is addressed, I will rerun.

**Review by youngjeong46 — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
