### PR TITLE
Add Dynatrace to the Docs and fixed keptn GitHub Repo link

### PR DESCRIPTION
**Pull request by heckelmann**
This PR will add the Dynatrace OneAgent Operator to the Docs (@shapirov103) and fixed the Link for the keptn AddOn after renaming the module.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by parkand1 — APPROVED** [review]
LGTM

**Review by askulkarni2 — APPROVED** [review]
LGTM!

**Comment by heckelmann** [comment]
Hello @askulkarni2 and @parkand1 

Thank you for the review... Do you have any chance to merge this PR?

Thank you!

**Review by shapirov103 — APPROVED** [review]
LGTM!

**Pull request merged**
