### PR TITLE
upgraded libraries, CDK set at 2.99.1, addon versions upgrades, core …

### PR DESCRIPTION
**Pull request by shapirov103**
…addon upgrades

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — CHANGES_REQUESTED** [review]
@shapirov103 Could we update Grafana Operator to v5.4.0 - https://github.com/grafana-operator/grafana-operator/releases/tag/v5.4.0

**Comment by shapirov103** [comment]
> @shapirov103 Could we update Grafana Operator to v5.4.0 - https://github.com/grafana-operator/grafana-operator/releases/tag/v5.4.0

addressed.  we need to divide up the update of certain addons, e.g. those based on the manifests, and other OCI charts that can not be tracked automatically.

**Pull request merged**
