### PR TITLE
Fixed tests, build issues, upgraded CDK and libs

### PR DESCRIPTION
**Pull request by shapirov103**
*Issue #, if available:*

*Description of changes:* In prep for the release fixing test and libs to merge the pull request that are currently in the queue.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — COMMENTED** [review]
@shapirov103 Changes look great. Only concern though is on the reoccurrence of this issue with all future e2e's. Could we do another e2e run before merge?

**Comment by shapirov103** [comment]
> @shapirov103 Changes look great. Only concern though is on the reoccurrence of this issue with all future e2e's. Could we do another e2e run before merge?

There is not much I can do other than temporarily remove ipv6 test to prevent timeout. The plan was to move to ABP.

**Comment by elamaran11** [comment]
> > @shapirov103 Changes look great. Only concern though is on the reoccurrence of this issue with all future e2e's. Could we do another e2e run before merge?
> 
> There is not much I can do other than temporarily remove ipv6 test to prevent timeout. The plan was to move to ABP.

Sounds good.

**Pull request merged**
