### PR TITLE
Adding ability to mark add-ons as control plane (deployed before capacity is added to the cluster)

### PR DESCRIPTION
**Pull request by shapirov103**
Adding ability to mark add-ons as control plane (deployed before capacity is added to the cluster)

*Issue #, if available:*

*Description of changes:*
All core add-ons now have a new `controlPlaneAddOn` attribute. If set to true, will deploy the add-on before any capacity is added to the cluster. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shapirov103** [comment]
@elamaran11 if you merge from this branch, you can deploy VPC CNI to the control plane before any capacity is added. Please let me know if that solves the custom network config issue.

**Comment by shapirov103** [comment]
e2e tests fail on delete. @youngjeong46 I see that there is an NLB provisioned with jupyterhub even thought ingress is set to false, is it by design?

**Comment by youngjeong46** [comment]
> e2e tests fail on delete. @youngjeong46 I see that there is an NLB provisioned with jupyterhub even thought ingress is set to false, is it by design?

The parameter is a bit of a misnomer. Enabling it exposes the front end hub as an ingress controller (using AWS ALB). Not enabling it just exposes the service via Network Load Balancer.

**Review by elamaran11 — APPROVED** [review]
LGTM @shapirov103 This worked fine as well along with my VPC CNI addon.

**Pull request merged**
